branches:
  only:
    - master
install:
  - cmd: pip install mkdocs
  
build_script:
  - cmd: mkdocs build --config-file mkdocs-au.yml
  # - cmd: mkdocs build --config-file mkdocs-nz.yml

artifacts:
  - path: humm-au
    name: humm-au
    type: zip
  # - path: humm-nz
  #   name: humm-nz
  #   type: zip

deploy:
  - provider: S3
    access_key_id: AKIAJIUIKUBZBXHSAR5Q
    secret_access_key:
      secure: 3pvBXjsWdGcaxmh5339WyN34ukiKJHyq+lfwxkyd+tfxu/0XgrQDsMfD5Uf44j+h
    bucket: docs.shophum.com.au
    region: ap-southeast-2
    unzip: true
    set_public: true
    artifact: humm-au
  # - provider: S3
  #   access_key_id: AKIAJIUIKUBZBXHSAR5Q
  #   secret_access_key:
  #     secure: 3pvBXjsWdGcaxmh5339WyN34ukiKJHyq+lfwxkyd+tfxu/0XgrQDsMfD5Uf44j+h
  #   bucket: docs.shophumm.co.nz
  #   region: ap-southeast-2
  #   unzip: true
  #   set_public: true
  #   artifact: humm-nz

notifications:
  - provider: Email
    to:
      - pit@shophumm.com.au
      - devadmin@shophumm.com.au
  - provider: Slack
    auth_token:
      secure: QWE2vFI2LUFAu+jx4lXHihtpPFoVi+ru0mHSC/BvsyXYcRvgh7Tc8zEEaKkj1n5V09+Ti39CvVooS3Y8VTn7PYC6lef2OrQQ+ivqkJL+lZI=
    channel: '#alerts'
